//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShadowsocksFreeServerFetcher.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShadowsocksFreeServerFetcher.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 不限 的本地化字符串。
        /// </summary>
        internal static string AnyCountry {
            get {
                return ResourceManager.GetString("AnyCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon AppIcon {
            get {
                object obj = ResourceManager.GetObject("AppIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 - [--]本地网络
        ///AD [AD]安道尔
        ///AE [AE]阿联酋
        ///AF [AF]阿富汗
        ///AG [AG]安提瓜和巴布达
        ///AI [AI]安圭拉
        ///AL [AL]阿尔巴尼亚
        ///AM [AM]亚美尼亚
        ///AO [AO]安哥拉
        ///AQ [AQ]南极洲
        ///AR [AR]阿根廷
        ///AS [AS]美属萨摩亚
        ///AT [AT]奥地利
        ///AU [AU]澳大利亚
        ///AW [AW]阿鲁巴
        ///AX [AX]奥兰
        ///AZ [AZ]阿塞拜疆
        ///BA [BA]波斯尼亚和黑塞哥维那
        ///BB [BB]巴巴多斯
        ///BD [BD]孟加拉国
        ///BE [BE]比利时
        ///BF [BF]布基纳法索
        ///BG [BG]保加利亚
        ///BH [BH]巴林
        ///BI [BI]布隆迪
        ///BJ [BJ]贝宁
        ///BL [BL]圣巴泰勒米
        ///BM [BM]百慕大
        ///BN [BN]文莱
        ///BO [BO]玻利维亚
        ///BQ [BQ]加勒比荷兰
        ///BR [BR]巴西
        ///BS [BS]巴哈马
        ///BT [BT]不丹
        ///BV [BV]布韦岛
        ///BW [BW]博茨瓦纳
        ///BY [BY]白俄罗斯
        ///BZ [BZ]伯利兹
        ///CA [CA]加拿大
        ///CC [CC]科科斯（基林）群岛
        ///CD [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string CountryName {
            get {
                return ResourceManager.GetString("CountryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退出 的本地化字符串。
        /// </summary>
        internal static string ExitMenuItem {
            get {
                return ResourceManager.GetString("ExitMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 脚本需要您指定 Shadowsocks 程序的文件地址以正常工作 的本地化字符串。
        /// </summary>
        internal static string FileNameNeeded {
            get {
                return ResourceManager.GetString("FileNameNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要 Shadowsocks 程序的文件地址 的本地化字符串。
        /// </summary>
        internal static string FileNameNeededTitle {
            get {
                return ResourceManager.GetString("FileNameNeededTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按国家或地区筛选服务器 的本地化字符串。
        /// </summary>
        internal static string FilterByCountry {
            get {
                return ResourceManager.GetString("FilterByCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 65536 -
        ///1 AU
        ///3 CN
        ///4 AU
        ///8 CN
        ///16 JP
        ///32 CN
        ///64 JP
        ///128 TH
        ///1 CN
        ///1 AU
        ///62 CN
        ///64 JP
        ///128 TH
        ///3 CN
        ///1 AU
        ///124 CN
        ///128 TH
        ///256 CN
        ///1 AU
        ///127 CN
        ///128 TH
        ///256 JP
        ///512 IN
        ///256 CN
        ///256 MY
        ///10 CN
        ///1 AU
        ///117 CN
        ///128 TH
        ///256 KR
        ///1024 CN
        ///1024 KR
        ///256 TH
        ///256 JP
        ///512 IN
        ///2048 CN
        ///128 MY
        ///128 SG
        ///256 JP
        ///512 TW
        ///256 HK
        ///256 PH
        ///512 IN
        ///1280 AU
        ///256 CN
        ///512 TH
        ///1024 CN
        ///1024 VN
        ///2048 CN
        ///512 HK
        ///512 JP
        ///1024 CN
        ///2048 JP
        ///4096 CN
        ///4096 KR
        ///1024 JP
        ///1024 CN
        ///10240 AU
        ///3791 TW
        ///1 NO
        ///304 TW
        ///512 KR
        ///384 AU
        ///128 TH
        ///153 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string IpTable {
            get {
                return ResourceManager.GetString("IpTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最后一次成功更新： {0} 的本地化字符串。
        /// </summary>
        internal static string LastUpdate {
            get {
                return ResourceManager.GetString("LastUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 需要启用至少一个服务器来源才能工作 的本地化字符串。
        /// </summary>
        internal static string NoFetcherEnabled {
            get {
                return ResourceManager.GetString("NoFetcherEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的服务器信息已是最新版本 的本地化字符串。
        /// </summary>
        internal static string NoNeedUpdate {
            get {
                return ResourceManager.GetString("NoNeedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无需更新 的本地化字符串。
        /// </summary>
        internal static string NoNeedUpdateTitle {
            get {
                return ResourceManager.GetString("NoNeedUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法获取有效地服务器信息 的本地化字符串。
        /// </summary>
        internal static string NoServerInfo {
            get {
                return ResourceManager.GetString("NoServerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有找到任何符合条件的服务器 的本地化字符串。
        /// </summary>
        internal static string NoValidServer {
            get {
                return ResourceManager.GetString("NoValidServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shadowsocks 自动更新 的本地化字符串。
        /// </summary>
        internal static string ProgramTitle {
            get {
                return ResourceManager.GetString("ProgramTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重新启动 Shadowsocks 程序 的本地化字符串。
        /// </summary>
        internal static string RestartShadowSock {
            get {
                return ResourceManager.GetString("RestartShadowSock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统启动时运行 的本地化字符串。
        /// </summary>
        internal static string RunInStartupMenuItem {
            get {
                return ResourceManager.GetString("RunInStartupMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用的服务器 的本地化字符串。
        /// </summary>
        internal static string ServerFilterRule {
            get {
                return ResourceManager.GetString("ServerFilterRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设置 Shadowsocks 程序路径... 的本地化字符串。
        /// </summary>
        internal static string SetOutputMenuItem {
            get {
                return ResourceManager.GetString("SetOutputMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shadowsocks 程序 (Shadowsocks.exe) 的本地化字符串。
        /// </summary>
        internal static string ShadowsockFileName {
            get {
                return ResourceManager.GetString("ShadowsockFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 自动更新时显示提示信息 的本地化字符串。
        /// </summary>
        internal static string ShowNotifyMenuItem {
            get {
                return ResourceManager.GetString("ShowNotifyMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新失败 的本地化字符串。
        /// </summary>
        internal static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即更新（双击图标） 的本地化字符串。
        /// </summary>
        internal static string UpdateNowMenuItem {
            get {
                return ResourceManager.GetString("UpdateNowMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器来源 的本地化字符串。
        /// </summary>
        internal static string UpdateSource {
            get {
                return ResourceManager.GetString("UpdateSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功更新并设置了{0}条服务器信息 的本地化字符串。
        /// </summary>
        internal static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新成功 的本地化字符串。
        /// </summary>
        internal static string UpdateSuccessTitle {
            get {
                return ResourceManager.GetString("UpdateSuccessTitle", resourceCulture);
            }
        }
    }
}
